

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 取消驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL显示
  global-config:
    db-config:
      id-type: auto