spring:
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: FlutterBackendDB
    password: Zust2022
    url: jdbc:mysql://hjhcj.com:3306/FlutterBackendDB?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 400
      # 配置获取连接等待超时的时间(毫秒)
      maxWait: 6000000        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 6000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      maxLifetime: 90000000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8082


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 取消驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL显示
  global-config:
    db-config:
      id-type: auto
