spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: FlutterBackendDB
    password: Zust2022
    url: jdbc:mysql://hjhcj.com:3306/FlutterBackendDB?characterEncoding=utf-8&serverTimezone=Asia/Shanghai

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8080